Lesson3 HW without 3rd
MChislov/python-testing-edu-public pull request #3
Opened 2022-10-23 18:20 UTC by MChislov

PR содержит задания 1,3,4. 
По второму заданию пока нет идей как закешировать функцию. Возвращаемые значения равны, но записаны в разных ячейках памяти по id. Можно ли попросить направить в нужную сторону для решения?

2022-10-23 21:15 UTC, alpakhomov requested changes
Оставил комменты по 1 и 2 заданиям (в первом тоже тесты не проходят). Поправь плз

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw2.py
> +    return func
Есть два основных способа это сделать:
- самостоятельно реализовать кэш (структуру данных которая будет хранить результаты вызова функции, и возвращать их из кэша если функция с такими аргументами уже вызывалась)
- lru_cache - только в текущем решении ты кэшируешь вызовы функции cache. А нужно кэшировать вызовы аргумента func. В документации есть упоминание, что lru_cache принимает опциональный параметр callable https://docs.python.org/3/library/functools.html#functools.lru_cache
В итоге нужно вернуть lru_cache с тем что необходимо кэшировать.

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw1.py
> +def check_five_entries_in_line(line: str) -> bool:
Функция проверяющая длину строки должна называться validate_line (она есть ниже, но просто возвращает true).
Плюс к этому валидатор должен возвращать либо True, либо False. Сейчас он возвращает строку или None.

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw1.py
> +    finally: return None
Тут все как-то очень сложно. Нам точно не нужно:
- кастить строку в datetime
- использовать except (здесь он вообще не нужен, ну и except без типа исключения - это всегда плохо, он поймает вообще любую ошибку)

Все что нужно сделать - проверить что дата (это должна быть последняя часть в строке) содержит паттерн описанный в задании. Ну и вернуть True/False

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw1.py
> +    with open("./data.txt") as ifile:
В функцию передается аргумент - путь к файлу с данными. Используй его, не нужно хардкодить значение.

Файл с результатами тоже стоит открывать в context manager `with open(...) as rfile, open(...) as wfile:`

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw1.py
> +            result_file.write("line with index: " + index.__str__() + " validation failures:")
В результирующем файле должна быть только строка с ошибкой и название валидатора, `foo@example.com 729.83 EUR accountName 2021-01:0 validate_date`, ничего больше

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw1.py
> +                if validation_result != None: result_file.write(validation_result)
validation_result это boolean, его не нужно писат в файл, только строку с ошибкой (см. выше)

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/hw1.py
> +    return result_file_path
Нужно вернуть абсолютный путь к файлу, сейчас возвращается захардкоженный.

2022-10-23 21:15 UTC, alpakhomov commented on Lesson3/test_hw1.py
> +
Из теста куда-то пропал импорт `from tempfile import NamedTemporaryFile`

2022-10-24 19:53 UTC, MChislov commented
@alpakhomov спасибо за ревью. 
В задании 1 не готовый вариант выложил. В данной версии надеюсь все в порядке. 
В задании 2 кешем разобрался через lru_cache.

2022-10-24 20:10 UTC, MChislov commented
Дополнение по 1 заданию. У меня валидация выдает ошибки на 746 строках. Последняя строка, на которой есть проблемы - 777. Но все 746 с проблемами. Тест падает, так как ожидаемое 777.

2022-10-24 20:25 UTC, alpakhomov requested changes
Еще комментарии по первому заданию, там тесты не проходят

2022-10-24 20:25 UTC, alpakhomov commented on Lesson3/hw1.py
> +    pattern_year_month_day = "(\d{4})\-(\d{2})\-(\d{2})"
Если не проходит тест на кол-во строк в файле - стоит проверить как работает эта регулярка https://regex101.com/r/OEgJaj/1
Например дата `2021-01-02020202` будет считаться валидной (хотя не должна)

2022-10-24 20:25 UTC, alpakhomov commented on Lesson3/hw1.py
> +    def __name__():
`__name__` не нужно переопределять. У любой функции по умолчанию есть такой атрибут:
```py
def foo():
    pass

print(foo.__name__)
# 'foo'
```

2022-10-24 20:25 UTC, alpakhomov commented on Lesson3/hw1.py
> +                if validation_result != True: wfile.write("line with index: " + index.__str__()+ " validation failed in method '" + validator.__name__ +"'\n")
- Строка в файл с ошибками все равно не корректно составляется. Должно быть "сама строка" + пробел + название валидатора. Больше никакого текста или индексов не нужно. Из-за этого первый тест падает. Посмотри плз еще раз описание задачи - там есть пример.
- `if validation_result != True` - так не стоит делать, принято писать `if not validation_result`. Индекс мне кажется совсем не нужен (или я чего-то не понимаю)

2022-10-25 09:42 UTC, MChislov commented on Lesson3/hw1.py
> +    pattern_year_month_day = "(\d{4})\-(\d{2})\-(\d{2})"
regex поменял на надежный вариант: `\ (\d{4})\-(\d{2})\-(\d{2})$|^(\d{4})\-(\d{2})\-(\d{2})$`

2022-10-25 09:43 UTC, MChislov commented on Lesson3/hw1.py
> +    def __name__():
убрал

2022-10-25 09:44 UTC, MChislov commented on Lesson3/hw1.py
> +                if validation_result != True: wfile.write("line with index: " + index.__str__()+ " validation failed in method '" + validator.__name__ +"'\n")
подправил. 

Индекс для информативности сообщения вводил. Но надо по правилам.

2022-10-25 10:41 UTC, alpakhomov approved these changes
Все ок, принято

2022-10-25 11:13 UTC, merged