Lesson4
MChislov/python-testing-edu-public pull request #4
Opened 2022-10-26 15:28 UTC by MChislov

ПР не содержит кода, который проходит все тесты. У меня вопрос по Teacher.check_homework(). По тестам выходит, что не передаются никакие параметры. В задании указано, что проверка любой Homework может осуществляться. Значит ли это, что осуществляется проверка работ с последней к первой? Тогда выходит, что после выполнения этого метода в строках 48 и 52 homework_done должен быть пустым, так как обе имеющиеся работы будут проверены. Где-то я заблуждаюсь очевидно. Только вот где?

2022-10-26 16:53 UTC, alpakhomov requested changes
В оригинальных тестах `check_homework` принимает один аргумент https://github.com/riassale/PythonCourseEpam/blob/main/Lecture%204/hw/test_hw1.py#L48 Не знаю куда у тебя они пропали, скопируй файл с тестами еще раз.

Тесты все равно не проходят из-за текущей реализации кэша, см. комменты

2022-10-26 16:53 UTC, alpakhomov commented on Lesson4/hw1.py
> +        if hw in Teacher.homework_done.keys():
Все, что касается работы с кэшом `homework_done` должно быть в классе Teacher. В этом методе мы просто проверяем дедлайн, и если он прошел  - бросаем исключение. Если нет - возвращаем результат дз.

Уже в методе проверки дз у учителя мы можем первым делом проверить, есть ли решение этого дз в кэше - если есть, ничего проверять не нужно, просто возвращаем True. Если нет  - проверяем, и если решение верное, кладем его в кэш и возвращаем True. Иначе просто возвращаем False.

Кэш должен быть общим для всех экземпляров класса Teacher (classmethod)

2022-10-26 16:53 UTC, alpakhomov commented on Lesson4/hw1.py
> +            Teacher.homework_done={}
Поскольку в этом методе мы обращаемся к классу, имеет смысл повесить аннотацию @classmethod и получать доступ к полям класса через `cls.homework_done...`

Ну и вместо *args можно просто использовать дефолтное значение - `def reset_results(hw=None)`

2022-10-26 19:57 UTC, MChislov commented
Спасибо за комментарии. По какой-то причине тесты у меня действительно были неправильные. Выкачал последние и подправил код. classmethod не использовал. Тесты начали проходить.

2022-10-27 11:22 UTC, alpakhomov approved these changes
Все ок, принято

2022-10-27 12:03 UTC, merged